---
# Installing Red Hat Satellite 6.4 Beta
- hosts: satellite
  become: yes
  environment: "{{satellite_environment}}"
  tasks:
    - name: "Set hosts file to {{sat_hostname}}.{{sat_domain}}"
      lineinfile: dest=/etc/hosts line="{{ansible_default_ipv4.address}} {{sat_hostname}}.{{sat_domain}} {{sat_hostname}}"
    - name: "Set hostname to {{sat_hostname}}.{{sat_domain}}"
      hostname:
        name: "{{sat_hostname}}.{{sat_domain}}"
    - name: Subscribe to RHSM via username/password/pool_id
      redhat_subscription:
        state: present
        username: "{{ rhn_username }}"
        password: "{{ rhn_password }}"
        pool: "{{ rhn_pool }}"
    - name: Disable all repositories
      command: /usr/sbin/subscription-manager repos --disable="*"
    - name: Enable Satellite repositories
      command: /usr/sbin/subscription-manager repos --enable="{{item}}"
      with_items: "{{ satellite_repos }}"
    - name: Update system packages
      yum: name="*" state=latest
    - name: Install firewalld
      yum: name=firewalld
      when: ansible_distribution_major_version>=7
    - name: Enable firewalld
      service: name=firewalld enabled=true state=started
      when: ansible_distribution_major_version>=7
    - name: Allow Satellite firewall ports
      firewalld: port={{item}} permanent=true state=enabled
      with_items: "{{ satellite_ports }}"
      when: ansible_distribution_major_version>=7
    - name: Restart firewalld
      service: name=firewalld state=restarted
      when: ansible_distribution_major_version>=7
    - name: Install Satellite
      yum: name=satellite state=present
    - name: Run Satellite Installer
      command: satellite-installer --scenario satellite --foreman-initial-organization "{{satellite_organization}}" --foreman-initial-location "{{satellite_location}}" --foreman-admin-username "{{satellite_admin_username}}" --foreman-admin-password "{{satellite_admin_password}}" --foreman-proxy-puppetca true --foreman-proxy-tftp true --enable-foreman-plugin-discovery
